[profile.default]
solc_version = "0.8.17"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = 'src'
out = 'out'
test = 'test/forge'
script = 'scripts/forge'
libs = ['lib']

[rpc_endpoints]
# Mainnets
mainnet = "${ETHEREUM_RPC}"
arbitrum = "${ARBITRUM_RPC}"
polygon = "${POLYGON_RPC}"

# Testnets
goerli = "${GOERLI_RPC}"
arbitrum_goerli = "${ARB_GOERLI_RPC}" 
mumbai = "${MUMBAI_RPC}"
local = "${LOCAL_RPC}"

[etherscan]
ethereum = { key = "${ETHEREUM_VERIFY_KEY}", url = "https://api.etherscan.io/api" }
arbitrum = { key = "${ARBITRUM_VERIFY_KEY}" }
polygon = { key = "${POLYGON_VERIFY_KEY}" }
arbiscan_goerli = { key = "${ARBITRUM_VERIFY_KEY}", url = "https://api-goerli.arbiscan.io/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true